In [121]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [122]:
pwd()

'C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests'

In [123]:
# Question 1

#  H0: mean1 = mean2
#  H1: mean1 <> mean2

diet=pd.read_csv("C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests\\Basic Statistics Assignment\\dietstudy.csv")

In [6]:
diet.head()

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [8]:
stats.ttest_rel(a = diet.tg0, b=diet.tg1)

# as pvalue is GREATER than 5%  hence NULL HYPOTHESIS is correct 

Ttest_relResult(statistic=1.708339375326079, pvalue=0.10817790329711016)

In [10]:
stats.ttest_rel(a = diet.wgt0, b=diet.wgt1)

# as pvalue is less than 5 and statistic is +ve, therefore a>b, as one of the measure is decreasing 
# hence diet is correct as weight has reduced.

Ttest_relResult(statistic=3.69481872265182, pvalue=0.0021619105203089487)

In [65]:
# Question 2

#  H0: mean1 = mean2
#  H1: mean1 < mean2

credit=pd.read_csv("C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests\\Basic Statistics Assignment\\creditpromo.csv")

In [66]:
credit.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [67]:
Standard= credit[credit['insert']=='Standard']['dollars']
Standard.head()
N_P= credit[credit['insert']=='New Promotion']['dollars']
N_P.head()

1    1403.807542
4    1513.563200
5    1729.627996
6    1609.705918
9    1854.489028
Name: dollars, dtype: float64

In [68]:
stats.ttest_ind(a =Standard, b=N_P)

# as pvalue is less than 5 and statistic is -ve, and a<b, hence PROMOTION IS effective 

Ttest_indResult(statistic=-2.2604227264649963, pvalue=0.024225996894147814)

In [80]:
# Question 3
poll=pd.read_csv("C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests\\Basic Statistics Assignment\\pollination.csv")

poll.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [73]:
#  H0: mean = 200
#  H1: mean <> 200

stats.ttest_1samp(a= poll.Seed_Yield_Plant, popmean = 200)

# as pvalue is less than 5 and statistic is -ve, hence reject null hypothesis 

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

In [78]:
Hand_SY = poll[poll['Group']== 'Hand']['Seed_Yield_Plant']
Natural_SY = poll[poll['Group']== 'Natural']['Seed_Yield_Plant']

Hand_FW = poll[poll['Group']== 'Hand']['Fruit_Wt']
Natural_FW = poll[poll['Group']== 'Natural']['Fruit_Wt']

Hand_SL = poll[poll['Group']== 'Hand']['Seedling_length']
Natural_SL = poll[poll['Group']== 'Natural']['Seedling_length']

In [127]:
 stats.ttest_ind(a= Hand_SY, b = Natural_SY, equal_var= False)

Ttest_indResult(statistic=13.958260515902547, pvalue=5.136161282685624e-11)

In [126]:
 stats.ttest_ind(a= Hand_SL, b = Natural_SL, equal_var= False)

Ttest_indResult(statistic=2.542229999657055, pvalue=0.021430608378161634)

In [124]:
 stats.ttest_ind(a= Hand_FW, b = Natural_FW, equal_var= False)
    
 # The null hypothesis is rejected and the pollinations are different   

Ttest_indResult(statistic=17.669989614440286, pvalue=4.306871213074868e-09)

In [88]:
# Question 4

#  H0: mean1 = mean2 = mean3 = mean4 = mean5 = mean6
#  H1: at least one is not equal

dvd=pd.read_csv("C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests\\Basic Statistics Assignment\\dvdplayer.csv")

dvd.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [86]:
Above_65 =  dvd[dvd['agegroup']== '65 and over']['dvdscore']
Btwn55_64 = dvd[dvd['agegroup']== '55-64']['dvdscore']
Btwn35_44 = dvd[dvd['agegroup']== '35-44']['dvdscore']
Btwn25_34 = dvd[dvd['agegroup']== '25-34']['dvdscore']
Btwn45_54 = dvd[dvd['agegroup']== '45-54']['dvdscore']
Under_25 =  dvd[dvd['agegroup']== 'Under 25']['dvdscore']

In [87]:
stats.f_oneway(Above_65,Btwn55_64,Btwn35_44,Btwn25_34,Btwn45_54,Under_25)

# Null Hypothesis rejected as pvalue is less than 5%

F_onewayResult(statistic=6.992526962676514, pvalue=3.087324905679639e-05)

In [98]:
# Question 5
sample=pd.read_csv("C:\\Users\\Deepika\\Desktop\\DSP\\DS\\Fundamental Stats & Stats tests\\Basic Statistics Assignment\\sample_survey.csv")

sample.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree  ...        agecat childcat news1 news2  news3  \
0     NaN     High school  ...      55 to 64      1-2    No    No     No   
1     NaN  Junior college  ...      25 to 34     None    No    No    Yes   
2    16.0     High school  ...      35 to 44      1-2    No    No     No   
3     NaN     High school  ...  Less than 25     None    No    No     No   
4     NaN        Bachelor  ...      35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [114]:
# 1)  HO: the vaiables are not related
#     H1: the variables are related 
    
t = pd.crosstab(sample.marital, sample.wrkstat, margins = True)
t

wrkstat        Keeping house  Other  Retired  School  Temporarily not working  \
marital                                                                         
Divorced                  25     12       53       7                        9   
Married                  200     16      168       9                       23   
Never married             35     14       17      60                       11   
Separated                 13      4        6       2                        1   
Widowed                   55      8      150       1                        2   
All                      328     54      394      79                       46   

wrkstat        Unemployed, laid off  Working full time  Working part-time  \
marital                                                                     
Divorced                         10                295                 35   
Married                          13                778                138   
Never married                    32                392                102   
Separated                         0                 58                  9   
Widowed                           3                 44                 20   
All                              58               1567                304   

wrkstat         All  
marital              
Divorced        446  
Married        1345  
Never married   663  
Separated        93  
Widowed         283  
All            2830

In [115]:
stats.chi2_contingency(observed = t)

# as pvalue is <5, there null is false and marital status and labour force status are related

(729.2421426572284,
 1.820339965538765e-127,
 40,
 array([[5.16918728e+01, 8.51024735e+00, 6.20932862e+01, 1.24501767e+01,
         7.24946996e+00, 9.14063604e+00, 2.46954770e+02, 4.79095406e+01,
         4.46000000e+02],
        [1.55886926e+02, 2.56643110e+01, 1.87254417e+02, 3.75459364e+01,
         2.18621908e+01, 2.75653710e+01, 7.44740283e+02, 1.44480565e+02,
         1.34500000e+03],
        [7.68424028e+01, 1.26508834e+01, 9.23045936e+01, 1.85077739e+01,
         1.07766784e+01, 1.35879859e+01, 3.67109894e+02, 7.12197880e+01,
         6.63000000e+02],
        [1.07787986e+01, 1.77455830e+00, 1.29477032e+01, 2.59611307e+00,
         1.51166078e+00, 1.90600707e+00, 5.14950530e+01, 9.99010601e+00,
         9.30000000e+01],
        [3.28000000e+01, 5.40000000e+00, 3.94000000e+01, 7.90000000e+00,
         4.60000000e+00, 5.80000000e+00, 1.56700000e+02, 3.04000000e+01,
         2.83000000e+02],
        [3.28000000e+02, 5.40000000e+01, 3.94000000e+02, 7.90000000e+01,
         4.600000

In [117]:
# 2)  HO: the vaiables are not related
#     H1: the variables are related 
    
u = pd.crosstab(sample.marital, sample.degree, margins = True)
u

degree         Bachelor  Graduate  High school  Junior college  \
marital                                                          
Divorced             58        29          241              45   
Married             251       123          686             108   
Never married       129        41          367              46   
Separated            12         3           58               3   
Widowed              28         9          148               6   
All                 478       205         1500             208   

degree         LT High school   All  
marital                              
Divorced                   70   443  
Married                   174  1342  
Never married              77   660  
Separated                  17    93  
Widowed                    92   283  
All                       430  2821

In [118]:
stats.chi2_contingency(observed = u)

# as pvalue is <5, there null hypothesis is false and marital status and education status are related

(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,   32.19248493,  235.55476781,   32.66359447,
           67.52570011,  443.        ],
        [ 227.39312301,   97.52215526,  713.57674583,   98.94930876,
          204.55866714, 1342.        ],
        [ 111.83268345,   47.9617157 ,  350.9393832 ,   48.66359447,
          100.60262318,  660.        ],
        [  15.75824176,    6.75824176,   49.45054945,    6.85714286,
           14.17582418,   93.        ],
        [  47.95249911,   20.56540234,  150.4785537 ,   20.86635945,
           43.1371854 ,  283.        ],
        [ 478.        ,  205.        , 1500.        ,  208.        ,
          430.        , 2821.        ]]))

In [119]:
# 3) HO: the vaiables are not related
#    H1: the variables are related 
    
v = pd.crosstab(sample.marital, sample.rincome, margins = True)
v

rincome        $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
marital                                                                        
Divorced                   6              37              37              45   
Married                   16              81              87             113   
Never married             17              74              59              60   
Separated                  0               1               6              12   
Widowed                    3               5               9               8   
All                       42             198             198             238   

rincome        $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
marital                                                                      
Divorced                  172              2              1              1   
Married                   483             17              9             20   
Never married             178             15             13             10   
Separated                  26              5              2              0   
Widowed                    25              1              2              1   
All                       884             40             27             32   

rincome        $6000 TO 6999  $7000 TO 7999  $8000 TO 9999  LT $1000   All  
marital                                                                     
Divorced                   6              6             11         2   326  
Married                   18             13             28        14   899  
Never married             16             14             16        21   493  
Separated                  2              5              4         3    66  
Widowed                    1              3              4         2    64  
All                       43             41             63        42  1848

In [120]:
stats.chi2_contingency(observed = v)

# as pvalue is <5, there null hypothesis is false and marital status and education status are related

(121.48376985191939,
 4.629034532421357e-06,
 60,
 array([[7.40909091e+00, 3.49285714e+01, 3.49285714e+01, 4.19848485e+01,
         1.55943723e+02, 7.05627706e+00, 4.76298701e+00, 5.64502165e+00,
         7.58549784e+00, 7.23268398e+00, 1.11136364e+01, 7.40909091e+00,
         3.26000000e+02],
        [2.04318182e+01, 9.63214286e+01, 9.63214286e+01, 1.15780303e+02,
         4.30041126e+02, 1.94588745e+01, 1.31347403e+01, 1.55670996e+01,
         2.09182900e+01, 1.99453463e+01, 3.06477273e+01, 2.04318182e+01,
         8.99000000e+02],
        [1.12045455e+01, 5.28214286e+01, 5.28214286e+01, 6.34924242e+01,
         2.35829004e+02, 1.06709957e+01, 7.20292208e+00, 8.53679654e+00,
         1.14713203e+01, 1.09377706e+01, 1.68068182e+01, 1.12045455e+01,
         4.93000000e+02],
        [1.50000000e+00, 7.07142857e+00, 7.07142857e+00, 8.50000000e+00,
         3.15714286e+01, 1.42857143e+00, 9.64285714e-01, 1.14285714e+00,
         1.53571429e+00, 1.46428571e+00, 2.25000000e+00, 1.50000000e+